'use strict'


module.exports=[
  {
    producto:"producto uno",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
    direccionImagen:"assets/images/collares2.jpg",
  },
  {
    producto:"producto dos",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
    direccionImagen:"assets/images/collares3.jpg",
  },
  {
    producto:"producto tres",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
    direccionImagen:"assets/images/collares4.jpg",
  },
  {
    producto:"producto cuatro",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
    direccionImagen:"assets/images/collares5.jpg",
  },
  {
    producto:"producto cinco",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
    direccionImagen:"assets/images/collares5.jpg",
  },
  {
    producto:"producto seis",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
    direccionImagen: "assets/images/collares7.jpg",
  },
  {
    producto:"producto siete",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
    direccionImagen:"assets/images/collares6.jpg",
  },
  {
    producto:"producto ocho",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
    direccionImagen:"assets/images/collares8.jpg",
  },
  {
    producto:"producto nueve",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
    direccionImagen:"assets/images/collares8.jpg",
  },
  {
    producto:"producto diez",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
    direccionImagen:"assets/images/ropa6.jpg",
  },
  {
    producto:"producto once",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
    direccionImagen:"assets/images/collares2.jpg",
  },
  {
    producto:"producto doce",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
    direccionImagen:"assets/images/ropa2.jpg",
  },
  {
    producto:"producto trece",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
    direccionImagen:"assets/images/collares5.jpg",
  },
  {
    producto:"producto catorce",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
    direccionImagen:"assets/images/collares9.jpg",
  },
  {
    producto:"producto quince",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
    direccionImagen:"assets/images/collares8.jpg",
  },
]
