'use strict'


module.exports=[
  {
    producto:"producto uno",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
  },
  {
    producto:"producto dos",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
  },
  {
    producto:"producto tres",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
  },
  {
    producto:"producto cuatro",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
  },
  {
    producto:"producto cinco",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
  },
  {
    producto:"producto seis",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
  },
  {
    producto:"producto siete",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
  },
  {
    producto:"producto ocho",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
  },
  {
    producto:"producto nueve",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
  },
  {
    producto:"producto diez",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
  },
  {
    producto:"producto once",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
  },
  {
    producto:"producto doce",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
  },
  {
    producto:"producto trece",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
  },
  {
    producto:"producto catorce",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
  },
  {
    producto:"producto quince",
    descripcion: "esto es una gran descripcion ",
    stock: 22,
    costo: "200",
    moneda: "pesos",
  },
]
